from setuptools import setup, find_packages

with open("docu/pypi_descr.md","r") as f:
    long_description = f.read()

setup(
    name = "agg_dim",
    version = "0.1.15",
    description="Data import modules for instruments used by AG Grothe",
    packages = find_packages(),
    long_description = long_description,
    long_description_content_type = "text/markdown",
    url = "https://github.com/matrup01/data_import_modules/",
    classifiers = ["License :: OSI Approved :: MIT License",
                   "Operating System :: OS Independent",
                   "Programming Language :: Python"],
    author = "Matthäus Rupprecht, Florian Wieland",
    author_email= "matthaeus.rupprecht@tuwien.ac.at",
    maintainer = "Matthäus Rupprecht",
    maintainer_email = "matthaeus.rupprecht@tuwien.ac.at",
    license = "MIT",
    licence_files = ("LICENSE"),
    install_requires = ["branca>=0.8.2",
                        "certifi>=2025.11.12",
                        "charset-normalizer>=3.4.4",
                        "contourpy>=1.3.3",
                        "cycler>=0.12.1",
                        "folium>=0.20.0",
                        "fonttools>=4.60.1",
                        "h5py>=3.15.1",
                        "idna>=3.11",
                        "Jinja2>=3.1.6",
                        "kiwisolver>=1.4.9",
                        "llvmlite>=0.45.1",
                        "MarkupSafe>=3.0.3",
                        "matplotlib>=3.10.7",
                        "numba>=0.62.1",
                        "numpy>=2.3.5",
                        "packaging>=25.0",
                        "pillow>=12.0.0",
                        "pyparsing>=3.2.5",
                        "python-dateutil>=2.9.0",
                        "requests>=2.32.5",
                        "six>=1.17.0",
                        "urllib3>=2.5.0",
                        "utm>=0.8.1",
                        "xyzservices>=2025.10.0",
                        ],
    extras_require={"dev" : ["twine>=6.2.0"]},
    python_requires=">=3.13.9",
    keywords = ["POPS","WIBS","SEN55","CCS811","OPC"]
    )
