from setuptools import setup, find_packages

with open("docu/pypi_descr.md","r") as f:
    long_description = f.read()

setup(
    name = "agg_dim",
    version = "0.2.3",
    description="Data import modules for instruments used by AG Grothe",
    packages = find_packages(),
    long_description = long_description,
    long_description_content_type = "text/markdown",
    url = "https://github.com/matrup01/data_import_modules/",
    classifiers = ["License :: OSI Approved :: MIT License",
                   "Operating System :: OS Independent",
                   "Programming Language :: Python"],
    author = "Matthäus Rupprecht, Florian Wieland",
    author_email= "matthaeus.rupprecht@tuwien.ac.at",
    maintainer = "Matthäus Rupprecht",
    maintainer_email = "matthaeus.rupprecht@tuwien.ac.at",
    license = "MIT",
    licence_files = ("LICENSE"),
    install_requires = ["branca>=0.8.2",
                        "certifi>=2026.4.22",
                        "charset-normalizer>=3.4.7",
                        "contourpy>=1.3.3",
                        "cycler>=0.12.1",
                        "folium>=0.20.0",
                        "fonttools>=4.62.1",
                        "h5py>=3.16.0",
                        "idna>=3.13",
                        "Jinja2>=3.1.6",
                        "kiwisolver>=1.5.0",
                        "llvmlite>=0.47.0",
                        "MarkupSafe>=3.0.3",
                        "matplotlib>=3.10.9",
                        "numba>=0.65.1",
                        "numpy>=2.4.4",
                        "packaging>=26.2",
                        "pillow>=12.2.0",
                        "pyparsing>=3.3.2",
                        "python-dateutil>=2.9.0",
                        "requests>=2.33.1",
                        "six>=1.17.0",
                        "urllib3>=2.7.0",
                        "utm>=0.8.1",
                        "xyzservices>=2026.3.0",
                        ],
    extras_require={"dev" : ["twine>=6.2.0",
                             "pdoc3>=0.11.6",
                             "setuptools>=82.0.1"]},
    python_requires=">=3.13.9",
    keywords = ["POPS","WIBS","SEN55","CCS811","OPC"]
    )
